import sys

with open('paper/final_paper.md', 'r') as f:
    content = f.read()

replacements = [
    (
        "## Abstract\n\nFlink and Kafka Streams both keep local state in RocksDB and both offer exactly-once processing over Kafka, but they place the cost of durability in different parts of the system: Flink coordinates asynchronous barrier-based checkpoints from a JobManager, while Kafka Streams replicates state changes to broker-held changelog topics and recovers by replaying them. Existing comparisons of the two systems mostly report worker-side throughput and stop there. This paper builds a small, reproducible benchmark, five workloads spanning stateless transforms, tumbling and sliding windows, and a stream-stream join, run on Apache Kafka 4.3.1 (KRaft mode), Kafka Streams 4.3.1, and Flink 2.2.0, and asks where visibility latency, backlog, and recovery time actually land. Results are derived from 5 independent trials to ensure statistical rigor. Every one of the baseline correctness executions matched its expected output with zero missing, unexpected, or duplicate records. Under sustained 100 events/sec load for 30 minutes, both engines held zero backlog growth on all four non-join workloads (W1-W4), and both showed the same qualitative pattern in their T0-T3 latency decomposition: a p99 engine-processing hop of 4-6 milliseconds on the stateless workloads (W1, W2) jumping to 4.3-6.2 seconds on the windowed ones (W3, W4), with Kafka Streams paying 23-42% more than Flink for the same jump. A matched multi-variable expert tuning comparison on both engines shows this cost is real and configuration-sensitive, but gated through mechanically different parts of each engine. Fault injection (JVM kill, broker kill, node loss, KRaft failover, object-store throttling, and changelog restore) shows the two architectures fail differently. This paper further establishes an environmental cost attribution model based on sustained resource utilization.",
        "## Abstract\n\nFlink and Kafka Streams both keep local state in RocksDB and both offer exactly-once processing over Kafka, but they place the cost of durability in different parts of the system: Flink coordinates asynchronous barrier-based checkpoints from a JobManager, while Kafka Streams replicates state changes to broker-held changelog topics and recovers by replaying them. Existing comparisons of the two systems mostly report worker-side throughput and stop there. This paper builds a small, reproducible benchmark, five workloads spanning stateless transforms, tumbling and sliding windows, and a stream-stream join, run on Apache Kafka 4.3.1 (KRaft mode), Kafka Streams 4.3.1, and Flink 2.2.0, and asks where visibility latency, backlog, and recovery time actually land. Every one of the baseline correctness executions matched its expected output with zero missing, unexpected, or duplicate records. Under sustained 100 events/sec load for 30 minutes, both engines held zero backlog growth on all four non-join workloads (W1-W4), and both showed the same qualitative pattern in their T0-T3 latency decomposition: a p99 engine-processing hop of 4-6 milliseconds on the stateless workloads (W1, W2) jumping to 4.3-6.2 seconds on the windowed ones (W3, W4), with Kafka Streams paying 23-42% more than Flink for the same jump. A matched tuning comparison on both engines shows this cost is real and configuration-sensitive, but gated through mechanically different parts of each engine. Fault injection (JVM kill, broker kill, and node loss) shows the two architectures fail differently."
    ),
    (
        "3. **RQ3, recovery and reprocessing behavior.** How do checkpoint or commit cadence and local-state loss affect recovery time, backlog drain, duplicate records, and downstream visibility delay?\n\nThis paper answers a bounded piece of each question. RQ1 has correctness evidence across all five workloads from 5 independent trials, and a fixed-rate and sustained-load latency picture (Section 5.2, 5.3). RQ2 includes an environmental and energy cost attribution driven from hardware metrics collected under load (Section 5.4). RQ3 features a full multi-mode fault-injection sweep across stateless and stateful workloads (Section 5.6).",
        "3. **RQ3, recovery and reprocessing behavior.** How do checkpoint or commit cadence and local-state loss affect recovery time, backlog drain, duplicate records, and downstream visibility delay?\n\nThis paper answers a bounded piece of each question. RQ1 has correctness evidence across all five workloads twice (a baseline and one repeat), and a fixed-rate and sustained-load latency picture (Section 5.2, 5.3). RQ2 includes resource utilization metrics collected under load (Section 5.4). RQ3 features a fault-injection sweep across the stateless identity workload (Section 5.6)."
    ),
    (
        "Both engines run against the same `apache/kafka:4.3.1` broker brought up in KRaft mode following the Apache Kafka quickstart \\[6\\], write output with `read_committed`-visible exactly-once delivery (Kafka Streams `exactly_once_v2`, Flink `EXACTLY_ONCE` Kafka sink), and are verified by the same external JSONL verifier. Flink 2.2.0 with `flink-connector-kafka` 5.0.0-2.2 \\[8\\] replaced an originally proposed Flink 2.3.x target after Apache Flink's downloads page \\[7\\] showed 5.0.0 as compatible with Flink 2.1.x and 2.2.x, not 2.3.x; this is a connector-compatibility correction, not a result-driven substitution, and is recorded here and in `docs/project_log.md`.",
        "Both engines run against the same `apache/kafka:4.3.1` broker brought up in KRaft mode following the Apache Kafka quickstart \\[6\\], write output with `read_committed`-visible exactly-once delivery (Kafka Streams `exactly_once_v2`, Flink `EXACTLY_ONCE` Kafka sink), and are verified by the same external JSONL verifier. Flink 2.2.0 with `flink-connector-kafka` 5.0.0-2.2 \\[8\\] replaced an originally proposed Flink 2.3.x target after Apache Flink's downloads page \\[7\\] showed 5.0.0 as compatible with Flink 2.1.x and 2.2.x, not 2.3.x; this is a connector-compatibility correction, not a result-driven substitution, and is recorded here and in `docs/project_log.md`. All experiments were run on a single dedicated machine sharing one Docker daemon, physical CPU, and disk."
    ),
    (
        "### 4.3 What has and has not been run\n\nThe original proposal (`proposal.md`, Section 4.3-4.5) specifies memory-pressure regimes, storage-tier sweeps, partition/parallelism sweeps, an expert-tuning protocol with a published trial budget, and a six-mode failure matrix. The current artifact has automated the execution of memory-pressure (Fit, Pressure, Starved), storage-tier (Local NVMe, Cloud Block), and partition sweeps (25 to 200). It has also executed correctness across all five workloads with 5 independent trials; fixed-rate latency; a 30-minute sustained-load stability check at 100 events/sec; resource-utilization sampling paired with an environmental energy estimation model; a multi-variable expert tuning search space; and a full fault-injection sweep across stateless and stateful workloads including KRaft failover, Object-Store throttling, and Changelog restore modes.",
        "### 4.3 What has and has not been run\n\nThe original proposal (`proposal.md`, Section 4.3-4.5) specifies memory-pressure regimes, storage-tier sweeps, partition/parallelism sweeps, an expert-tuning protocol with a published trial budget, and a six-mode failure matrix. The current artifact has executed correctness across all five workloads twice (a baseline and one repeat); fixed-rate latency; a 30-minute sustained-load stability check at 100 events/sec; resource-utilization sampling; a matched tuning comparison (varying the commit/checkpoint interval); and a fault-injection sweep (JVM kill, broker kill, node loss) across the stateless `W1` workload."
    ),
    (
        "Both engines processed all five workloads twice (a baseline run and an independent `repeat1` run) against the shared deterministic input. All 20 runs matched their expected output exactly: zero missing, zero unexpected, and zero duplicate records in every case, across output counts ranging from 199 (`W3`) to 11,024 (`W5`). Appendix A1 has the full table. This establishes that both engines implement the intended workload semantics under `read_committed` exactly-once delivery before any latency or failure claim is asked to mean anything.",
        "Both engines processed all five workloads twice (a baseline run and an independent `repeat1` run) against the shared deterministic input. All 20 runs matched their expected output exactly: zero missing, zero unexpected, and zero duplicate records in every case, across output counts ranging from 199 (`W3`) to 11,024 (`W5`). The supplementary material has the full table. This establishes that both engines implement the intended workload semantics under `read_committed` exactly-once delivery before any latency or failure claim is asked to mean anything."
    ),
    (
        "At 20 records/sec with 100 input records, both engines pass every workload's correctness check while p99 end-to-end visibility delay ranges from about 2.6 seconds (`W1`, both engines) up to about 7.1 seconds (Kafka Streams `W4`) and 5.8 seconds (Flink `W4`). Kafka Streams and Flink each ran a 10/20/40 records/sec sweep plus a second 20/sec run; full numbers are in Appendix A3. Two things stand out even at this small scale. First, the windowed workloads (`W3`, `W4`) carry roughly two to three times the p99 of the stateless ones (`W1`, `W2`) for both engines, consistent with final-window suppression holding output until the window closes rather than emitting continuously. Second, the rate direction is inconsistent for the windowed workloads: p99 falls from 10/sec to 40/sec for both engines on `W3` and `W4` (for example, Kafka Streams `W3` p99 goes from 11,631 ms at 10/sec to 3,943 ms at 40/sec). At 100 total input records, a higher production rate means the fixed-size input finishes sooner relative to the window boundaries the generator places it against, so this is very likely a small-sample artifact of how few windows a 100-record run touches, not a real property of the engines. Section 5.3's 100 events/sec, 30-minute runs (18,000 times more events) are the more trustworthy source for windowed-workload latency, and are read against this section for exactly that reason.",
        "At 20 records/sec with 100 input records, both engines pass every workload's correctness check while p99 end-to-end visibility delay ranges from about 2.6 seconds (`W1`, both engines) up to about 7.1 seconds (Kafka Streams `W4`) and 5.8 seconds (Flink `W4`). Kafka Streams and Flink each ran a 10/20/40 records/sec sweep plus a second 20/sec run; full numbers are in the supplementary material. Two things stand out even at this small scale. First, the windowed workloads (`W3`, `W4`) carry roughly two to three times the p99 of the stateless ones (`W1`, `W2`) for both engines, consistent with final-window suppression holding output until the window closes rather than emitting continuously. Second, the rate direction is inconsistent for the windowed workloads: p99 falls from 10/sec to 40/sec for both engines on `W3` and `W4` (for example, Kafka Streams `W3` p99 goes from 11,631 ms at 10/sec to 3,943 ms at 40/sec). At 100 total input records, a higher production rate means the fixed-size input finishes sooner relative to the window boundaries the generator places it against, so this is very likely a small-sample artifact of how few windows a 100-record run touches, not a real property of the engines. Section 5.3's 100 events/sec, 30-minute runs (18,000 times more events) are the more trustworthy source for windowed-workload latency, and are read against this section for exactly that reason."
    ),
    (
        "### 5.4 Resource utilization\n\nA `docker stats` sampler (`src/stream_state_bench/resource_monitor.py`) polls CPU, memory, and network I/O for the engine and broker containers at a fixed interval, and calculates estimated environmental and energy costs (PUE, gCO2eq/h) to quantify infrastructure sustainability overhead. Kafka Streams' worker memory rises with workload state, from a mean 117.5 MiB on stateless `W1` to 157.0 MiB on stateful `W4`. Flink's worker sits at a blended mean of 377.6 MiB across its whole stability sweep, above any single Kafka Streams figure, consistent with a heavier baseline JVM and cluster-runtime footprint independent of workload state.",
        "### 5.4 Resource utilization\n\nA `docker stats` sampler (`src/stream_state_bench/resource_monitor.py`) polls CPU, memory, and network I/O for the engine and broker containers at a fixed interval. Kafka Streams' worker memory rises with workload state, from a mean 117.5 MiB on stateless `W1` to 157.0 MiB on stateful `W4`. Flink's worker sits at a blended mean of 377.6 MiB across its whole stability sweep, above any single Kafka Streams figure, consistent with a heavier baseline JVM and cluster-runtime footprint independent of workload state."
    ),
    (
        "`scripts/run-failure-test.sh` injects six failure modes across stateless (`W1`) and stateful (`W3`, `W4`) workloads. The modes include `jvm_kill`, `broker_kill`, `node_loss` (removing anonymous volumes), `kraft_failover`, `s3_throttling`, and `changelog_restore` (wiping Kafka Streams' internal state). Every run across 5 independent trials matched all expected output records with zero missing, unexpected, or duplicate records, ensuring no failure caused an externally visible correctness violation, only a latency spike.",
        "`scripts/run-failure-test.sh` injects three failure modes across the stateless (`W1`) workload. The modes include `jvm_kill`, `broker_kill`, and `node_loss` (removing anonymous volumes). Every run matched all expected output records with zero missing, unexpected, or duplicate records, ensuring no failure caused an externally visible correctness violation, only a latency spike."
    ),
    (
        "**Broker failure costs the two engines the same thing, then a different thing.** Both engines show `t1-t0` (ingestion) jump to roughly 8.5 to 8.8 seconds under `broker_kill`, functionally identical, because both are equally blocked from writing to a Kafka topic while the broker container is down; this is a shared-infrastructure cost, not an engine property. Where they diverge is downstream: Kafka Streams' `t3-t2` (commit-and-consume) hop absorbs an extra 9.4 seconds under the same failure, while Flink's stays close to its steady-state 1 second. One plausible reading is that Kafka Streams' EOS-v2 transactional commit protocol needs the transaction coordinator, itself broker-hosted, to be healthy before a pending commit can close, so a broker outage delays the commit even after the broker is technically back, whereas Flink's checkpoint-and-two-phase-commit path to the Kafka sink recovers on a different schedule. This artifact has one run per engine per failure mode, not enough to separate a real architectural difference from a single noisy trial, and that caveat is treated as binding, not decorative (Section 7).",
        "**Broker failure costs the two engines the same thing, then a different thing.** Both engines show `t1-t0` (ingestion) jump to roughly 8.5 to 8.8 seconds under `broker_kill`, functionally identical, because both are equally blocked from writing to a Kafka topic while the broker container is down; this is a shared-infrastructure cost, not an engine property. Where they diverge is downstream: Kafka Streams' `t3-t2` (commit-and-consume) hop absorbs an extra 9.4 seconds under the same failure, while Flink's stays close to its steady-state 1 second. We hypothesize that Kafka Streams' EOS-v2 transactional commit protocol needs the transaction coordinator, itself broker-hosted, to be healthy before a pending commit can close, so a broker outage delays the commit even after the broker is technically back, whereas Flink's checkpoint-and-two-phase-commit path to the Kafka sink recovers on a different schedule. This remains a hypothesis to be tested in future work, as this artifact has one run per engine per failure mode, not enough to separate a real architectural difference from a single noisy trial."
    ),
    (
        "These findings are backed by 5 independent trials for all evaluations, spanning stateless and stateful workloads across a comprehensive six-mode fault injection matrix, robust hardware and environmental cost estimations, and automated multi-parameter scaling sweeps. The resulting benchmark now offers a complete, rigorous empirical foundation for evaluating stream processing infrastructure costs.\n\n## References",
        "The resulting benchmark provides an initial empirical foundation for evaluating stream processing infrastructure costs.\n\n## References"
    )
]

for orig, new in replacements:
    if orig not in content:
        print(f"NOT FOUND: {orig[:50]}...")
    else:
        content = content.replace(orig, new)

# Truncate at Appendix
idx = content.find("## Appendix: Full Per-Run Tables")
if idx != -1:
    content = content[:idx]

with open('paper/final_paper.md', 'w') as f:
    f.write(content)

print("Done")
