import json

with open("src/stream_state_bench/kafka_latency_probe.py", "r") as f:
    content = f.read()

content = content.replace('def load_expected_outputs(path: Path) -> dict[str, tuple[str, ...]]:\n    outputs: dict[str, tuple[str, ...]] = {}', 'def load_expected_outputs(path: Path) -> dict[str, dict[str, object]]:\n    outputs: dict[str, dict[str, object]] = {}')
content = content.replace('outputs[record_id] = source_ids', 'payload = json.loads(stripped)\n            outputs[record_id] = {\n                "source_ids": source_ids,\n                "window_end_ms": payload.get("window_end_ms"),\n            }')
content = content.replace('for comp in ["t1_t0_ms", "t2_t1_ms", "t3_t2_ms"]:', 'for comp in ["write_to_input_append_latency_ms", "input_append_to_result_emission_latency_ms", "l_visibility_ms", "l_closure_ms"]:')
content = content.replace('            "event_id", "t0_ms", "t1_ms", "t2_ms", "t3_ms", \n            "t1_t0_ms", "t2_t1_ms", "t3_t2_ms", "latency_ms"', '            "event_id", "t0_ms", "t1_ms", "t2_ms", "t3_ms", \n            "write_to_input_append_latency_ms", "input_append_to_result_emission_latency_ms", "l_visibility_ms", "l_closure_ms", "latency_ms"')
content = content.replace('    consumer_isolation: str,\n    input_sources: list[tuple[Path, str]] | None = None,\n    docker_network: str | None = None,\n) -> dict[str, object]:', '    consumer_isolation: str,\n    allowed_lateness_ms: int = 0,\n    input_sources: list[tuple[Path, str]] | None = None,\n    docker_network: str | None = None,\n) -> dict[str, object]:')

content = content.replace('        producer = producer_for(topic)\n        assert producer.stdin is not None\n        producer.stdin.write(line + "\\n")\n        producer.stdin.flush()\n        send_times[input_event_id(line)] = time.time_ns()', '        producer = producer_for(topic)\n        assert producer.stdin is not None\n        send_times[input_event_id(line)] = time.time_ns()\n        producer.stdin.write(line + "\\n")\n        producer.stdin.flush()')

# receive_ns
content = content.replace('        record_id, source_ids = output_record_id_and_sources(line)\n        expected_source_ids = expected_outputs.get(record_id)\n        if expected_source_ids is None:', '        record_id, source_ids = output_record_id_and_sources(line)\n        expected_record = expected_outputs.get(record_id)\n        if expected_record is None:\n            unmatched_outputs.append(record_id)\n            continue\n        expected_source_ids = expected_record["source_ids"]\n        expected_window_end_ms = expected_record.get("window_end_ms")\n        if False:')

# samples
content = content.replace('        latency_ms = round(t3_ms - t0_ms, 3)\n        sample = {\n            "event_id": record_id,\n            "t0_ms": t0_ms,\n            "t1_ms": t1_ms,\n            "t2_ms": t2_ms,\n            "t3_ms": t3_ms,\n            "t1_t0_ms": round(t1_ms - t0_ms, 3) if t1_ms is not None else None,\n            "t2_t1_ms": round(t2_ms - t1_ms, 3) if t2_ms is not None and t1_ms is not None else None,\n            "t3_t2_ms": round(t3_ms - t2_ms, 3) if t3_ms is not None and t2_ms is not None else None,\n            "latency_ms": latency_ms,\n        }', '        latency_ms = round(t3_ms - t0_ms, 3)\n        l_closure_ms = None\n        if t2_ms is not None and expected_window_end_ms is not None:\n            l_closure_ms = round(t2_ms - (expected_window_end_ms + allowed_lateness_ms), 3)\n\n        sample = {\n            "event_id": record_id,\n            "t0_ms": t0_ms,\n            "t1_ms": t1_ms,\n            "t2_ms": t2_ms,\n            "t3_ms": t3_ms,\n            "write_to_input_append_latency_ms": round(t1_ms - t0_ms, 3) if t1_ms is not None else None,\n            "input_append_to_result_emission_latency_ms": round(t2_ms - t1_ms, 3) if t2_ms is not None and t1_ms is not None else None,\n            "l_visibility_ms": round(t3_ms - t2_ms, 3) if t3_ms is not None and t2_ms is not None else None,\n            "l_closure_ms": l_closure_ms,\n            "latency_ms": latency_ms,\n        }')

content = content.replace('    parser.add_argument("--consumer-isolation", default="read_committed")\n    parser.add_argument("--docker-network", type=str)\n    args = parser.parse_args()', '    parser.add_argument("--consumer-isolation", default="read_committed")\n    parser.add_argument("--allowed-lateness-ms", type=int, default=0)\n    parser.add_argument("--docker-network", type=str)\n    args = parser.parse_args()')

content = content.replace('        timeout_sec=args.timeout_sec,\n        consumer_isolation=args.consumer_isolation,\n        input_sources=input_sources,\n        docker_network=args.docker_network,\n    )', '        timeout_sec=args.timeout_sec,\n        consumer_isolation=args.consumer_isolation,\n        allowed_lateness_ms=args.allowed_lateness_ms,\n        input_sources=input_sources,\n        docker_network=args.docker_network,\n    )')

with open("src/stream_state_bench/kafka_latency_probe.py", "w") as f:
    f.write(content)
